Build Task MVP
v1kramb/azure-logic-apps-pipeline-tasks pull request #1
Opened 2023-06-29 23:54 UTC by v1kramb

I've tried to show all the files which are relevant via extraneous comments. This is a pretty much a PR for the entire repo though.

2023-06-30 19:59 UTC, nidhi-pathak requested changes

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
nit: makeAbsolute->ConvertToAbsolutePath

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
Do we need this - tl.debug('makeAbsolute:' + normalizedPath);

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
Space after L62

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
Better naming for getOptions method

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
There are couple of formatting issues in getOptions method and line space after end of if/else block

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
Missing doc for sevenZipArchive - can you also explain somewhere what is sevenZip in general doing as there are multiple reference to it in the file

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
private methods's doc comments missing at multiple places

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
reordering of methods recommended in file for better readability.
-Consider moving main method as first method in file, then all method in order they are called inside main method and then so on.....

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/copyfiles.ts
>  import fs = require('fs');
Better naming for stats method

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/copyfiles.ts
>  import fs = require('fs');
Can we have better naming for let targetFolder: string = "project_output". May be <logicappname>_output?

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/copyfiles.ts
>  import fs = require('fs');
Can we ignore files in funcignore and gitignore for packaging?

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/copyfiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/copyfiles.ts
Maybe we can track it as a seperate task but we need to do 1 addl thing after copy i.e

The folder structure we will have in repo is:-
```
 Repo
     -Deployment
         -LogicApp1
             -Parameters
                  -parameters.json
         -LogicApp2
               <same as above>
     -LogicApp1
               <all files of project>
               -parameters.json
     -LogicApp2
               <all files of project>
               -parameters.json
```
When a build task is called, it will be in context of a LogicApp lets say LogicApp1. Before we zip files and after copy, we need to replace the parameter.json file in LogicApp with corresponding parameter file in Deployment folder. 

IMHO, we should add this work with a validation what if the folder structure is as above and if deployment folder contains parameter.json, then do a replace after copy and before zip.

We can discuss more on this if not clear.

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/azurelogicappsstandardbuild.ts
>      private static sourceFolder: string;
Instead of source folder as input we should take specifics from customer like **repo name** and **logic app name** to construct equivalent of '$(System.DefaultWorkingDirectory)/azure-devops-sample/logic'

In addition, we should optionally ask for "deployment folder name" default to "Deployment" as its value - this is for copying over parameters files. (Added detailed description in a comment in copyfiles.ts)

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/azurelogicappsstandardbuild.ts
> -    // Logic App
Consider taking TargetFolder as input as well

2023-06-30 19:59 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/azurelogicappsstandardbuild.ts
>      private static defaultWorkingDir: string;
Where are we taking  artifact: '$(logicAppCIArtifactName)'?

2023-06-30 19:59 UTC, nidhi-pathak commented on vss-extension.json
>      "manifestVersion": 1,
Please revise following contents of Readme.md with the help of Parth and Wagner.

AzureLogicAppsStandardBuild - consolides copy/zip for Logic App source folder

AzureLogicAppsStandardRelease - (TODO) consolidate Azure Functions web app deploy + App Settings config

2023-06-30 23:50 UTC, mireedmsft approved these changes

2023-06-30 23:50 UTC, mireedmsft commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> +// Adapted from => https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
The "main" method in this class, and others, is a bit confusing.. is this the normal convention for Typescript? I would expect a single main method for the entire task.

So I would change this class name to be FileArchiver.. and then your main method here would be Archive.

Ignore me, however, if this is normal convention for Typescript :)

2023-06-30 23:50 UTC, mireedmsft commented on AzureLogicAppsStandardBuildV0/copyfiles.ts
> +// Adapted from => https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/copyfiles.ts
Same thing here.. I would name this class "FileCopier" and call your main method "Copy"

2023-06-30 23:50 UTC, mireedmsft commented on vss-extension.json
> +    "version": "1.0.4",
This should be reverted to 1.0.0 when we publish.

2023-06-30 23:50 UTC, mireedmsft commented on AzureLogicAppsStandardBuildV0/package.json
> +  "version": "1.0.1",
revert to 1.0.0 when we publish

2023-07-03 19:57 UTC, ynauls commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
@nidhi-pathak , do we want to create unit tests for both archiveFiles and CopyFiles?  These files are being ported/copied from pipelines repo.  unfortunately, there is no package to import, copying is the next best option.  These tasks are fully tested in their own repository project.

2023-07-03 20:02 UTC, ynauls commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
@nidhi-pathak , copyFiles and archiveFiles are being ported/copied from azure pipelines repo.  They are fully unit tested in their respective projects.  ideally, if there is a new version, we would copy over the latest and greatest.  The only unit test that is a must is one to ensure the version being copied is compatible with our custom task. Thoughts?

cc @v1kramb

2023-07-06 19:25 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
I agree with your proposal. One suggestion i would have is although copyfile and archive files are independently verified and tested but having an end to end test, much like an integration test, to cover when those actions are executed sequentially the input is a pointer to repo and output is a zipped content will suffice. Specially if we are going to add copy+replace of parameter.json file in the build process, it will become even more meaningful to have an end to end test.

2023-07-07 23:25 UTC, v1kramb reviewed
Added more comments

2023-07-07 23:25 UTC, v1kramb commented on AzureLogicAppsStandardBuildV0/copyfiles.ts
>  import fs = require('fs');
This will be P1, after end-to-end testing is successful.

2023-07-07 23:25 UTC, v1kramb commented on AzureLogicAppsStandardBuildV0/archivefiles.ts
> -// Adapted from: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/archivefiles.ts
done

2023-07-07 23:25 UTC, v1kramb commented on AzureLogicAppsStandardBuildV0/azurelogicappsstandardbuild.ts
>      private static sourceFolder: string;
This will be P1. Copying over params should be done simultaneously with providing optional input.

2023-07-07 23:25 UTC, v1kramb commented on AzureLogicAppsStandardBuildV0/azurelogicappsstandardbuild.ts
>      private static defaultWorkingDir: string;
We aren't - the user would be pasting the artifact name into the CI YAML, which would look like this:

`- job: logic_app_build
   steps:
   - task: AzureLogicAppsStandardBuild@X
      inputs:
          - sourceFolder
          - archiveFile (optional) 
   - task: PublishPipelineArtifact@1
     inputs:
         - targetPath
         - artifactName
         - publishLocation
`

This reduces constraints on the user (e.g. using different publishing tasks, changing target path, etc.). It's also more consistent to have the user paste in an artifact name because the user will need to manually paste the artifact name in the IAC YAML anyway.

2023-07-07 23:25 UTC, v1kramb commented on AzureLogicAppsStandardBuildV0/azurelogicappsstandardbuild.ts
> -    // Logic App
Talked to Yerko about this earlier. Since the target folder is temporary, we're not sure if there's much value to having a custom name for it - maybe as an optional input to prevent overwrites? A better solution to preventing overwrites would be to append a UID to an arbitrary name and passing it to the copier and archiver.

That being said, do you think there may be merit in having the archiveFile (archivefiles.ts, L26) be an optional input? Is there value in having the name of the zip file be customizable (e.g. replacing the BuildId with a more readable name)?

2023-07-10 20:30 UTC, nidhi-pathak commented on AzureLogicAppsStandardBuildV0/azurelogicappsstandardbuild.ts
>      private static sourceFolder: string;
Sorry i didnt understand. Can you elaborate on P1?

2023-08-04 18:04 UTC, closed without merging